// Explicit bindings keep Electron main-process bundling from emitting
// side-effect-only imports with undefined re-export references.
import {
  AGENTS_DIR_NAME,
  AGENTS_BACKUPS_DIR_NAME,
  AGENTS_SETTINGS_JSON,
  AGENTS_MCP_JSON,
  AGENTS_MODELS_JSON,
  AGENTS_SYSTEM_PROMPT_MD,
  AGENTS_AGENTS_MD,
  AGENTS_LAYOUTS_DIR,
  AGENTS_DEFAULT_LAYOUT_JSON,
  AGENTS_AGENT_PROFILES_DIR,
  AGENTS_TASKS_DIR,
  getAgentsLayerPaths,
  layerHasAnyAgentsConfig,
  loadAgentsLayerConfig,
  loadAgentsPrompts,
  loadMergedAgentsConfig,
  splitConfigIntoAgentsFiles,
  writeAgentsPrompts,
  writeAgentsLayerFromConfig,
  findAgentsDirUpward,
} from "../../../../../packages/core/src/agents-files/modular-config"

export {
  AGENTS_DIR_NAME,
  AGENTS_BACKUPS_DIR_NAME,
  AGENTS_SETTINGS_JSON,
  AGENTS_MCP_JSON,
  AGENTS_MODELS_JSON,
  AGENTS_SYSTEM_PROMPT_MD,
  AGENTS_AGENTS_MD,
  AGENTS_LAYOUTS_DIR,
  AGENTS_DEFAULT_LAYOUT_JSON,
  AGENTS_AGENT_PROFILES_DIR,
  AGENTS_TASKS_DIR,
  getAgentsLayerPaths,
  layerHasAnyAgentsConfig,
  loadAgentsLayerConfig,
  loadAgentsPrompts,
  loadMergedAgentsConfig,
  splitConfigIntoAgentsFiles,
  writeAgentsPrompts,
  writeAgentsLayerFromConfig,
  findAgentsDirUpward,
}
export type { AgentsLayerPaths, SplitAgentsConfig } from "../../../../../packages/core/src/agents-files/modular-config"
